export const FETCH_GUESTS = 'FETCH_GUESTS';
export const FETCH_GUEST = 'FETCH_GUEST';
export const CREATE_GUEST = 'CREATE_GUEST';
export const UPDATE_GUEST = 'UPDATE_GUEST';
export const DELETE_GUEST = 'DELETE_GUEST';
export const UNSELECT_GUEST = 'UNSELECT_GUEST';